### ISSUE TITLE
Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead. 

### ISSUE THREAD

**Issue by penjual** [niftylettuce/react-native-loading-spinner-overlay#10]
react-native@0.25
node_modules/react-native-loading-spinner-overlay/lib/index.js

Please update it with the latest react-native version.

Thank you

**Comment by niftylettuce** [comment]
@penjual can you confirm this fixes the issue for you? https://github.com/niftylettuce/react-native-loading-spinner-overlay/pull/11 -- try to `npm install react-native-loading-spinner-overlay@latest`.
