### ISSUE TITLE
missing Portal.js - react-native 0.26

### ISSUE THREAD

**Issue by TUNER88** [niftylettuce/react-native-loading-spinner-overlay#12]
Seems like `Portal.js` is no more part of react-native package.
```const Portal = require('react-native/Libraries/Portal/Portal.js');```
https://github.com/niftylettuce/react-native-loading-spinner-overlay/blob/master/src/index.js#L26

![simulator screen shot 19 may 2016 11 17 11](https://cloud.githubusercontent.com/assets/1565397/15388704/8a2f10d2-1db3-11e6-806f-915d2bc6a1ce.png)

**Comment by rajkissu** [comment]
I have the same issue as well, +1

**Comment by KaanErkol** [comment]
+1

**Comment by ivpusic** [comment]
+1

**Comment by duketwo** [comment]
+1, any workaround?

**Comment by rajkissu** [comment]
I removed the Portal dependency in PR #13, looks like Modal works just fine with Android in RN 0.26

**Comment by ryanhanwu** [comment]
+1

**Comment by alexjhannan** [comment]
+1

**Comment by jeveloper** [comment]
+1

**Comment by csandeep** [comment]
+1

**Comment by yusufseyrek** [comment]
+1

**Comment by radik909** [comment]
+1

**Comment by niftylettuce** [comment]
Released in v0.1.1, sorry for delay, my GitHub notifications were screwed up

**Comment by jeveloper** [comment]
Thank you kindly !
