### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by danielbm** [niftylettuce/react-native-loading-spinner-overlay#22]
Hi. I am getting this error, which seems related to #20 

> /home/daniel/memox/memox/memoxnative/node_modules/promise/lib/done.js:10
>       throw err;
>       ^
> Error: Couldn't find preset "react-native-stage-0" relative to directory "/home/daniel/memox/memox/memoxnative/node_modules/react-native-loading-spinner-overlay"
>     at /home/daniel/memox/memox/memoxnative/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
>     at Array.map (native)
>     at OptionManager.resolvePresets (/home/daniel/memox/memox/memoxnative/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
>     at OptionManager.mergePresets (/home/daniel/memox/memox/memoxnative/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
>     at OptionManager.mergeOptions (/home/daniel/memox/memox/memoxnative/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
>     at OptionManager.addConfig (/home/daniel/memox/memox/memoxnative/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
>     at OptionManager.findConfigs (/home/daniel/memox/memox/memoxnative/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
>     at OptionManager.init (/home/daniel/memox/memox/memoxnative/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
>     at File.initOptions (/home/daniel/memox/memox/memoxnative/node_modules/babel-core/lib/transformation/file/index.js:223:65)
> TransformError: /home/daniel/memox/memox/memoxnative/node_modules/react-native-loading-spinner-overlay/src/index.js: Couldn't find preset "react-native-stage-0" relative to directory "/home/daniel/memox/memox/memoxnative/node_modules/react-native-loading-spinner-overlay"
> :app:bundleReleaseJsAndAssets FAILED
> 

I am using react native 0.28.0, and react-native-loading-spinner-overlay 0.2.2.

Apparently the fix for #20 did not work for me. Am I doing something wrong?

**Comment by niftylettuce** [comment]
Sorry, we need to put `babel-preset-stage-0` in `dependencies` I believe.  In the meanwhile, you can simply do `npm i --save-dev babel-preset-stage-0` to fix this.

**Comment by slayrbear** [comment]
any idea of when this can be fixed?

**Comment by slayrbear** [comment]
For a temporary fix for this issue in your React Native project, you actually want to run the command `npm install babel-preset-react-native-stage-0 --save` and add .babelrc file your root project directory with `{
  "presets": ["react-native-stage-0"]
}`

More information here https://github.com/skevy/babel-preset-react-native-stage-0.

**Comment by niftylettuce** [comment]
What is the preferred approach here?  I was given the suggestion to not compile out a lib folder from the src directory, but I'm really not sure how to support the community without doing so.  Should I remove the `.babelrc` file?  Is it even needed?

**Comment by niftylettuce** [comment]
See release v0.2.3 on NPM, `npm i --save react-native-loading-spinner-overlay@0.2.3`.  Thank you!

**Comment by danielbm** [comment]
Thanks @niftylettuce and @slayrbear !

**Comment by luisfuertes** [comment]
I have the v0.2.3 and react-native v0.28.0 and same error.

**Comment by deju** [comment]
@slayrbear It works for me.

**Comment by slayrbear** [comment]
Very weird. It was working for me, now it's not. 

@deju Can you confirm if this is working for you once more? Make sure you restart the package manager, etc and try again. 

@niftylettuce Any ideas to permanently fix this? My commit should have gotten the error fix by adding babel-preset-react-native-stage-0 as a dev dependency to the package.

Anyways, the temporary fix I mentioned earlier in this thread will fix this in your RN project.

**Comment by luisfuertes** [comment]
Some news?

**Comment by faizan-tariq-confiz** [comment]
I am getting the same error. 
Used npm i --save react-native-loading-spinner-overlay@0.2.3
and .babelrc file already exists 
Any suggestion to resolve this issue????

**Comment by munzur** [comment]
@faizan-tariq-confiz 
npm -i babel-preset-react-native-stage-0 --save-dev

i think this will solve your problem.

**Comment by faizan-tariq-confiz** [comment]
I have already tried this, and its not working

**Comment by ivpusic** [comment]
+1

**Comment by luisfuertes** [comment]
I did @slayrbear response and fixed it:
```
For a temporary fix for this issue in your React Native project, you actually want to run the command npm install babel-preset-react-native-stage-0 --save and add .babelrc file your root project directory with { "presets": ["react-native-stage-0"] }

More information here https://github.com/skevy/babel-preset-react-native-stage-0.
```

**Comment by tuxtux00** [comment]
Hi there,
Will a permanent fix come for this issue? 

Regards

**Comment by niftylettuce** [comment]
Taking a look here..

**Comment by niftylettuce** [comment]
See release v0.3.0, install with `npm i --save react-native-loading-spinner-overlay`.

**Comment by niftylettuce** [comment]
I just tested this out on latest version of React Native and also took this screenshot showing this is now working as of `v0.3.0` without any extra steps needed.  Sorry about that guys, I had been distracted with another more prioritized project.  If someone wants to have collaborator status on here and NPM for future updates, I would gladly share it.  Thank you for reporting the issue @danielbm

**Comment by niftylettuce** [comment]
<img width="393" alt="screen shot 2016-07-31 at 1 58 47 pm" src="https://cloud.githubusercontent.com/assets/523141/17278267/30ccf61e-5727-11e6-8b61-c0a81452312d.png">
