### ISSUE TITLE
Wrong orientation of modal dimensions in landscape (android)

### ISSUE THREAD

**Issue by Chris-Petty** [niftylettuce/react-native-loading-spinner-overlay#25]
![screen shot 2016-08-10 at 12 16 13 pm](https://cloud.githubusercontent.com/assets/7684221/17537894/763d9904-5ef4-11e6-9133-9c0a124e099d.png)

I gave it a red background for eye sore testing. So my app runs in landscape mode only. Using this component the dimensions of the spinner/modal don't appear to be respecting that - looks like it renders portrait dimensions at 0,0 coordinates. The Spinner component is located in the root view component.

**Comment by nehajoshi90** [comment]
I got the same issue.
 Also the overlay does get displayed but the spinner was not displayed in lollipop but worked perfectly fine in marshmallow device. What can be the issue?

**Comment by nehajoshi90** [comment]
I got the same issue.
Also the overlay does get displayed but the spinner was not displayed in lollipop but worked perfectly fine in marshmallow device. What can be the issue?

**Comment by bhushanjawle** [comment]
Same issue. @Chris-Petty were you able to resolve this. If yes, can you please share your approach here.

**Comment by niftylettuce** [comment]
I'll gladly accept a PR and another maintainer here!  My time with RN is super limited for the next bit of time 😦

**Comment by Chris-Petty** [comment]
@bhushanjawle No sorry. My colleague made a fork of RN to make animations that looped properly (and didn't lag the function that was taking long enough to warrant the indicator) and created a loading modal for us. In that process, didn't come across this problem.

Unfortunately that doesn't help this repo. 

Obviously having a fork of RN isn't preferable if it can be avoided, though. So an npm module of our solution won't be happening unfortunately.

**Comment by Chris-Petty** [comment]
All that said, a possible trail towards a solution might be here:

https://corbt.com/posts/2016/03/16/detecting-orientation-in-react-native.html

**Comment by SandroMachado** [comment]
This is a RN issue: https://github.com/facebook/react-native/issues/7708 and it was fixed in RN 0.37.0.

@Chris-Petty can you please confirm?

**Comment by Chris-Petty** [comment]
@SandroMachado Thanks for pointing this out. I've updated a branch of our project to RN 0.38.0 and and threw this overlay onto a random page. Seems to work fine!

I'm happy enough to close this issue.

**Comment by SandroMachado** [comment]
Great 👍
