### ISSUE TITLE
Is it possible to have a custom gif/icon for loading?

### ISSUE THREAD

**Issue by omrihq** [niftylettuce/react-native-loading-spinner-overlay#27]

**Comment by niftylettuce** [comment]
I'm sure you could fork this and add that feature!  That'd be awesome.

**Comment by b8ne** [comment]
Is this still wanted? I have a bit of time over the next few days.  Only learning RN now but simple packages like this help the learning curve so am happy to help where I can.

**Comment by omrihq** [comment]
That would be great. I haven't had a chance to sit down on this because it's just not pressing for my project, but it would definitely be a great learning project if you want to take on it!

**Comment by SandroMachado** [comment]
Closed by #37
