### ISSUE TITLE
Portal closes modal while component is updating

### ISSUE THREAD

**Issue by artem-russkikh** [niftylettuce/react-native-loading-spinner-overlay#3]
Only on android

Is it problem of react-native-loading-spinner-overlay?

If so, seems to be that problem in this line https://github.com/niftylettuce/react-native-loading-spinner-overlay/blob/master/src/index.js#L93
It should be:
```javascript
if (prevProps.visible && !this.props.visible) Portal.closeModal(tag);
```

Make PR?

**Comment by niftylettuce** [comment]
make a PR please
