### ISSUE TITLE
LOOKING FOR NEW MAINTAINER

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/react-native-loading-spinner-overlay#38]

**Comment by SandroMachado** [comment]
@niftylettuce since I am using this library, I can handle it. Please let me know WDYT.

**Comment by niftylettuce** [comment]
okay whats your NPM username @SandroMachado

**Comment by SandroMachado** [comment]
Hi @niftylettuce, my username at NPM is `sandromachado`.

**Comment by niftylettuce** [comment]
@SandroMachado you now have owner access on NPM - thanks!
