### ISSUE TITLE
Show warning on RN 0.19

### ISSUE THREAD

**Issue by pewh** [niftylettuce/react-native-loading-spinner-overlay#4]
It seems RN 0.19 change the behavior of how Portal work. I got this error when running on RN 0.19.
`Warning: Each child in array or iterator should have a unique "key" props. Check the render method of "Portal".`

**Comment by bcalik** [comment]
Same here on 0.20.

**Comment by FladeX** [comment]
Same problem, 0.20

**Comment by tal952** [comment]
+1

**Comment by niftylettuce** [comment]
@pewh Where did they change behavior, and how?

**Comment by niftylettuce** [comment]
Closed per #8

**Comment by liu-yuhuan** [comment]
could anyone help me, how to update the fixed package?
my package without src folder even i run npm update react-native-loading-spinner-overlay
warning message show up all the time, please help me~
thanks

**Comment by niftylettuce** [comment]
@liu-yuhuan What version do you have in `package.json`?  What version is in the `./node_modules/react-native-loading-spinner-overlay/package.json` file?  Also, can you share a screenshot?

**Comment by liu-yuhuan** [comment]
my react native version is 0.20 
and package info as below 

"name": "react-native-loading-spinner-overlay",
"version": "0.0.6",
"description": "The only pure React Native Native iOS and Android loading spinner (progress bar indicator) overlay",
"main": "lib/index.js",

**Comment by niftylettuce** [comment]
Can you try to upgrade to `v0.0.8`?  Do it with `npm install --save react-native-loading-spinner-overlay@latest`.  The latest version in NPM is `v0.0.8`, and you seem to have only `v0.0.6`.

**Comment by liu-yuhuan** [comment]
thank you!!!!
