### ISSUE TITLE
Spinner size

### ISSUE THREAD

**Issue by brascene** [niftylettuce/react-native-loading-spinner-overlay#40]
Hi! Is there an option to decrease spinner size? e.g. to place it in a smaller modal window? 
e.g. if I put it inside modal, it is shown over whole screen, can its size be reduced?

Thanks!

**Comment by SandroMachado** [comment]
Hi @brascene,

so do you want to apply this component to only a specific part of the screen?

**Comment by brascene** [comment]
Hi @SandroMachado , sorry for delay, and yes, I would like to apply it in e.g. small pop-up window.

**Comment by SandroMachado** [comment]
Unfortunately using this library to do that is not possible. This library uses the `Modal` component from RN, that basically is a new `Scene` that is pushed over the current view filling whole the screen.
