### ISSUE TITLE
How to allow for space at the bottom for TabbarIOS

### ISSUE THREAD

**Issue by skyride99** [niftylettuce/react-native-loading-spinner-overlay#5]
At the bottom I need to show the tabbar, and allow for navigation. 

The modal blocks the entire screen. Not allowing for click events. Changing the background and container do not help. The Modal is blocking the whole screen.

**Comment by peng051410** [comment]
+1

**Comment by niftylettuce** [comment]
@skyride99 Ah, this is for progress indicators that completely block and wait until something finishes in order to hide it.

**Comment by niftylettuce** [comment]
PR is welcome to add this feature!  @skyride99 @peng051410 I'd love to add you guys as collaborators/owners of this repo.  More support the better.

**Comment by skyride99** [comment]
I have used the other modal box and it works. react-native-modalbox. Is that possible to put in the project? A pull request?

**Comment by niftylettuce** [comment]
yeah send a PR over!

**Comment by davidjb** [comment]
This would be good for working with a navbar (eg with https://github.com/aksonov/react-native-router-flux); being able to leave space [at the top] & still interact with the controls.  Will see about a PR, unless you were close @skyride99?
