### ISSUE TITLE
Key prop warning

### ISSUE THREAD

**Issue by dayAlone** [niftylettuce/react-native-loading-spinner-overlay#6]
![Warning](http://s0s0.ru/gyazo/03.03.16/890a21fbd3f05b38358bda431c9750a8c1b339.png)

**Comment by tal952** [comment]
+1

**Comment by niftylettuce** [comment]
Really not sure where this error comes from in the codebase, do you guys?

https://github.com/niftylettuce/react-native-loading-spinner-overlay/blob/master/src/index.js

**Comment by dayAlone** [comment]
If add random key to parent View in _renderSpinner, this warning no longer displayed

**Comment by niftylettuce** [comment]
@dayAlone Can you submit a PR?

**Comment by niftylettuce** [comment]
Closed per #8
