### ISSUE TITLE
show double circle where setState({visable:true}) , after setState({visable:false})

### ISSUE THREAD

**Issue by yulinho** [niftylettuce/react-native-loading-spinner-overlay#9]
show double circle where setState({visable:true}) , after setState({visable:false}),but just one spinner element.
bug happened on android  5.1.1.
![567467526914258829](https://cloud.githubusercontent.com/assets/8208362/14759052/c90d4bb0-0946-11e6-8316-755cdec72956.jpg)

**Comment by alexhsieh-handy** [comment]
same issue

**Comment by niftylettuce** [comment]
can either of you submit patch?

**Comment by niftylettuce** [comment]
Does this still occur?  If so let me know and I'll re-open.
